name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare files
      run: |
        mkdir InternalConversations
        # Move everything except .git and README.md into the InternalConversations folder
        find . -maxdepth 1 ! -name .git ! -name .github ! -name InternalConversations ! -name . ! -name README.md -exec mv {} InternalConversations/ \;

    -   name: Archive repository
        run: |
            zip -r "${GITHUB_REF_NAME}.zip" InternalConversations
            cp "${GITHUB_REF_NAME}.zip" latest.zip

    -   name: Create version.txt
        run: echo "${GITHUB_REF_NAME}" > version.txt

    -   name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: ./
            server-dir: './'

    -   name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: ${GITHUB_REF_NAME}.zip
            asset_name: "InternalConversations.zip"
            tag: ${{ github.ref }}
            overwrite: true
